### ISSUE TITLE
Calculates drive size differently from other apps

### ISSUE THREAD

**Issue by probonopd** [raspberrypi/imagewriter#24]
Imager calculates the drive size differently from other apps. As a result, it displays a 4 GB microSD card as "3 GB":

![](https://user-images.githubusercontent.com/2480569/76158352-6f5a6e80-60eb-11ea-9ada-8d47b417cef5.png)

The "Disks" application in Gnome calls it "4 GB", as does the vendor on the packaging:

![](https://user-images.githubusercontent.com/2480569/76158358-8600c580-60eb-11ea-9f20-9a23ee5fde39.png)

**Comment by maxnet** [comment]
Some vendors are even selling 15.500.000 bytes cards as 16 GB, because they know certain operating systems round the number anyway.

Should we follow that practice or not?

![kde-does-display-real-size](https://user-images.githubusercontent.com/1123701/76163308-42d34080-6145-11ea-81b5-b3a0e23b35d5.png)

What should be displayed is not universal though. E.g. KDE does not round, and displays GiB.

**Comment by bsimmo** [comment]
It should use the convention of the OS you are using the program on.  That is what users will expect.

**Comment by maxnet** [comment]
So what should the convention of the Linux OS be?
KDE GNOME, some magic detection of the Window manager used? :-)

**Comment by probonopd** [comment]
I'd say, typical nominal values of such media are 1, 2, 4, 8, 16, 32, 64, 128, 256, 512 MB/GB/TB. Other values are very, very rare for storage media.

**Comment by lurch** [comment]
> Other values are very, very rare for storage media.

I believe it's only SD cards that _always_ have this power-of-2 capacity sizing (give or take whatever size the manufacturer _actually_ puts on the card)? Other flash-based media (e.g. SSDs or USB thumb drives) might also have similar power-of-2 capacities, but this definitely **isn't** the case for HDDs. I wouldn't call hard-drives very rare :wink:

**Comment by lurch** [comment]
> It should use the convention of the OS you are using the program on. That is what users will expect.

You could also argue that a cross-platform application ought to be expected to work the same on each OS it runs on? :man_shrugging: :smiling_imp: 

@maxnet Is there a reason for displaying "3,965,190,144 bytes" as "3 GB" rather than "3.9 GB" ?

**Comment by bsimmo** [comment]
> Imager calculates the drive size differently from other apps. As a result, it displays a 4 GB microSD card as "3 GB":
> 
> ![](https://user-images.githubusercontent.com/2480569/76158352-6f5a6e80-60eb-11ea-9ada-8d47b417cef5.png)
> 
> The "Disks" application in Gnome calls it "4 GB", as does the vendor on the packaging:
> 
> ![](https://user-images.githubusercontent.com/2480569/76158358-8600c580-60eb-11ea-9f20-9a23ee5fde39.png)

What does 
lsblk --bytes 
give ?
It is what the program uses to get the size info (I believe). (with some formatting options and all drives)

**Comment by probonopd** [comment]
```
sdb      8:16   1   3965190144  0 disk 
├─sdb1   8:17   1    536870912  0 part /media/me/LIBREELEC
└─sdb2   8:18   1     33554432  0 part /media/me/STORAGE
```

**Comment by maxnet** [comment]
> It is what the program uses to get the size info (I believe). (with some formatting options and all drives)

The rounding down to a whole number is my doing, rather than something lsblk did.
Just thought it would be weird to round the number up instead, as that could appear to the user that a 4 GB image could be written to probonopd's slightly smaller than 4 GB card, while that certainly will fail.

Adding a decimal like suggested by lurch could also be a good middle ground.

**Comment by bsimmo** [comment]
Decimal place sound, certainly better than loosing almost 1GB good
 or 
use whatever the OS rounds to (so without --bytes)?
