### ISSUE TITLE
Imager does not save .img files correctly while other program does.

### ISSUE THREAD

**Issue by 4k3or3et** [raspberrypi/imagewriter#27]
Hi All

For some reason Raspberry Pi Imager for Windows does not save .img files correctly to SD card. The weird thing is that Win32 Disk Imager saves the same .img file properly one the same card with the same card reader.

I tried two SD card readers and four SD cards, every time getting the same result.

Basically not matter what .img file I am trying to save using RPi Imager it always fail after verification. Also there are no partitions at all after saving .img file on SD (i was checking that in gparted). 

I tried my own backups and official Buster img file downloaded from raspberrypi.org.

When i select from RPi Imager Buster OS which is downloaded from Internet by the program then it saves it on SD card correctly!!?

So it looks like problem lays down in saving .img images.

Anybody can help what is the reason why it does not save  partition table correctly when saving .img files?

Anybody has the same issue?

Thank you.

**Comment by maxnet** [comment]
There is a bug in which verification fails if the image size is not dividable by 128 KB.
You should not have a problem writing official Raspbian images which are a nice round number of megabytes large though.

**Comment by 4k3or3et** [comment]
> There is a bug in which verification fails if the image size is not dividable by 128 KB.
> You should not have a problem writing official Raspbian images which are a nice round number of megabytes large though.

Thank you for your reply. As I wrote before, even writing official buster image leaves SD card unpartitioned...

**Comment by maxnet** [comment]
What image exactly?

It is normal for partition table to be empty if validation failed.
First part of card (including partition table) is not written until everything complete. Otherwise there is a large chance Windows will be accessing the card and modifying things while we are still using it.

**Comment by maxnet** [comment]
Hmm, thinking about it, the same bug may also occur in a few other circumstances if you are using uncompressed raw images.
Does it work correctly if you feed it an official Raspbian .zip file without uncompressing it first?

If so, then it likely the same bug. Which has already been fixed in git. But did not make it to a new release yet.

**Comment by 4k3or3et** [comment]
I am taking about this image:

https://downloads.raspberrypi.org/raspbian/images/raspbian-2020-02-14/2020-02-13-raspbian-buster.zip

No matter if try to save it from .zip or after decompressing in .img format. Both ways fails for me...

Thanks a lot for digging into my problem. 

Can you tell me please if there and change log i could watch for any chagnes and new version of this tool?

**Comment by maxnet** [comment]
>Can you tell me please if there and change log

During development the commit list has all code changes: https://github.com/raspberrypi/imagewriter/commits/
E.g. "Fix verifying on images that are not dividable by block size" is the change that should fix this.

Will leave the question whether there will be a more human readable (aimed at normal users rather than developers) changelog on the site, open for someone else.

**Comment by ghollingworth** [comment]
Fixed and released, please go to the Raspberry Pi Downloads pages to update
